# Generated by Django 5.0 on 2023-12-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, verbose_name='Тикер')),
                ('volume', models.IntegerField(verbose_name='Объем')),
                ('volume_weighted', models.FloatField(verbose_name='Взвешенный объем')),
                ('open_price', models.FloatField(verbose_name='Цена открытия')),
                ('close_price', models.FloatField(verbose_name='Цена закрытия')),
                ('high_price', models.FloatField(verbose_name='Максимальная цена')),
                ('low_price', models.FloatField(verbose_name='Минимальная цена')),
                ('timestamp', models.DateTimeField(verbose_name='Временная метка')),
                ('trades_count', models.IntegerField(verbose_name='Количество сделок')),
            ],
            options={
                'verbose_name': 'Информация о стоимости акции',
                'verbose_name_plural': 'Информация о стоимости акций',
            },
        ),
    ]
